phusion/passenger-docker

- Makefile
- README.md
- image/enable_repos.sh
- image/install.sh
- image/jruby1.7.sh
- image/nginx-passenger.sh
This PR adds support for building a JRuby Docker image as well. The version of JRuby in Debian and Ubuntu at the moment is ancient (4 years old), so we have to take a bit more manual steps to download it and so forth.
> Added support for JRuby (1.7.18)

- README.md
Hi,
The README lists Python version 3.0, which is not suitable for my current project (Python 3.4 SSLContext). 
Since this image derives from Ubuntu 14.04 I suspected that the documentation might be out of date, and I decided to check the actual Python version before using a different image:
```
user@dockerhost:~$ docker run --rm -t -i phusion/passenger-full bash -l
root@9e0515ccf45a:/# python3
Python 3.4.0 (default, Jun 19 2015, 14:20:21)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
root@9e0515ccf45a:/#
```
I would appreciate it if you update the README to reflect this Python version.
> List the correct Python 3 version in the README

- README.md
It looks like the .deb in [the repo](https://oss-binaries.phusionpassenger.com) is running Passenger 5, but the README states version 4.
Found via `docker run -it phusion/passenger-ruby22 bash -c "apt-get update; apt-cache show passenger"`, which reports `Version: 1:5.0.7-1~trusty1`.
> Passenger version should be 5 in README.md

- README.md
the enterprise install instructions still reference trusty instead of xenial.  Fixed.
> fixes enterprise instructions

- Changelog.md
It seems this version is not tagged and not released at [GitHub release page](https://github.com/phusion/passenger-docker/releases).
> fix changelog version

- README.md
Because there was a comment after a Dockerfile instruction, I had this this cryptic error as a result:
COPY failed: stat /var/lib/docker/tmp/docker-builder779111576/home/app/webapp: no such file or directory
Moving the comment to its own line fixed this.
> Move comment on README Dockerfile on its own line

- README.md
- image/install.sh
- image/nginx-passenger.sh
A critical deadlock bug was noticed yesterday and a hotfix release was sent out. This patches 2.5.4 -> 2.5.5
https://www.ruby-lang.org/en/news/2019/03/15/ruby-2-5-5-released/
> Update ruby 2.5.4 -> 2.5.5 for deadlock hotfix.

- image/buildconfig
Bundler is now installed by default with the latest versions of RVM[1]
1. https://github.com/rvm/rvm/pull/4413
fixes #260
> Update buildconfig to remove bundler

- README.md
Now the latest passenger-docker image uses Phusion Passenger 6.
> Fix README.md: Passenger's version

- README.md
Docker hub uses `/u` for user links and `/r` for project links. The previous link in the README led to a blank page, so I changed it to the proper link to the project page.
> Fix docker hub link

- CHANGELOG.md
- README.md
1.0.13 added support for 3.0.0 but this was missing from the readme and changelog.
The master branch also currently has 3.0.1 support.  
I was waiting for a new image to be pushed due to the lack of docs until i realised it was actually in there so ive updated the docs.
> Added ruby 3.x to readme and changelog

- .github/workflows/main.yml
In some cases running `make build_all` take a lot of time and cannot be finished with success (ex. Apple Silicon).
Lets have free to use GH-action that will starts on every push to `master` branch or on every push to PR into `master`
> Add Gihub Action to run make build_all

- image/ruby_support/install_ruby_utils.sh
I noticed that it was still using node 10.19.0, in the ruby images. This was preventing us from updating some of our node dependencies, since they want a more recent version of node. This PR updates the install script to install node by just running the nodejs install script used in the nodejs image, instead of just installing node via the default apt.
> install nodejs using the nodejs install script for ruby

- README.md
- image/nodejs.sh
As noted in this ![issue](https://github.com/phusion/passenger-docker/issues/363) the LTS version of 18 has been active since October of 2022. In addition v16 will be hitting end of life in September of this year.
> Replace Node 16 LTS with 18 LTS

- .dockerignore
- Makefile
- image/Dockerfile
- image/Dockerfile.base
- image/buildconfig
- image/finalize.sh
- image/install_base.sh
- image/install_image.sh
- image/update_baseimage.sh
make build_all on current master takes ~288 minutes on my system
With this PR, that drops to ~220 minutes. It also avoids downloading ~1900 packages from the Ubuntu mirrors.
Building a single image will take a few seconds longer, but any additional image in the same build cycle will be noticeably faster, especially in the not-native arch where even dpkg is slow.
The output images should be more or less identical to current master. I did add some dpkg log cleanup, though, but that should be the only effective difference.
Feedback welcome. I tried a few different ways to accomplish this and this was the least intrusive, but I'm not going to claim to be a docker expert.
> Reduce time required to build_all with a temporary base image

- image/install_openssl1.1.sh
This just updates the self-built OpenSSL 1.1.1 used for Ruby 3.0 .
> Use latest openssl 1.1.1w (only with Ruby 3.0)

- .github/workflows/main.yml
- Makefile
This does not change the default behaviour of make.
1) Substantially reduces the size of the Makefile with macros.
2) Allows overriding VERSION and NAME during build to easily build, tag, and upload to a custom repository, without editing the Makefile or manually creating tags after build.
3) Allows building for only a single architecture without editing the Makefile .
Adds support for the following environment variables during make:
VERSION (if set, this overrides the VERSION set in Makefile)
NAME (if set, this overrides the repository and image base name set in Makefile)
BUILD_AMD64 (if this exists and is set to 0, the amd64 images will not be built)
BUILD_ARM64 (if this exists and is set to 0, the arm64 images will not be built)
... make sure these are not set in your environment if …
> QoL improvements for working on or self-hosting image

- CHANGELOG.md
- README.md
- image/nginx-passenger.sh
- image/ruby_support/finalize.sh
Updates docs and misc scripts to reflect Ruby 3.3 addition.
> Add extra pieces to finish Ruby 3.3.0 addition

- image/nginx-passenger.sh
- image/runit/nginx-term
Modifies the default signal sent to nginx when terminating the container to allow graceful exit.
Closes https://github.com/phusion/passenger-docker/issues/149
> Use SIGQUIT instead of SIGTERM to shutdown nginx.

- image/utilities.sh
This fixes a bug that doesn't affect the official build images, but did bite me building the images locally.
Basically, "file" isn't in baseimage, but does get pulled in by some development tools. If the image being built doesn't need those because of caching, then file doesn't end up being in the end image.
All this does is explicitly install file, which is present in all current official build images anyway.
> Explicitly install "file"

- .github/workflows/main.yml
- CHANGELOG.md
- Makefile
- README.md
Python 3.13.0 has been released. This adds a versioned image for it.
> Add a Python 3.13 image

- .github/workflows/main.yml
- CHANGELOG.md
- Makefile
- README.md
- image/Dockerfile
- image/nginx-passenger.sh
- image/ruby-3.4.1.sh
- image/ruby_support/finalize.sh
Adds a Ruby 3.4 image (using ruby 3.4.1) and uses Ruby 3.4 by default in passenger-full and non-ruby images.
> Add a Ruby 3.4 image

- README.md
There is a small pronoun error and a serial comma/subject enhancement, if I may be so bold 🙏 
Thank you for your excellent software. You all rock! 🏆
> Update README.md with a small grammatical syntax edit 
